# Generated by Django 4.1.7 on 2023-03-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("korean", models.BooleanField(default="True")),
                ("chinese", models.BooleanField(default="True")),
                ("japanese", models.BooleanField(default="True")),
                ("western", models.BooleanField(default="True")),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
                ("location", models.CharField(default="", max_length=50)),
                ("latitude", models.FloatField(default=0.0)),
                ("longitude", models.FloatField(default=0.0)),
                (
                    "foodtype",
                    models.CharField(
                        choices=[
                            ("korean", "한식"),
                            ("japanese", "일식"),
                            ("chinese", "중식"),
                            ("western", "양식"),
                            ("e.t.c", "기타"),
                        ],
                        default="korean",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
