# Generated by Django 4.1.7 on 2023-03-07 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matjipmrk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 7, 16, 29, 43, 831553)
            ),
        ),
    ]
