# Generated by Django 4.1.7 on 2023-03-13 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matjipmrk", "0002_restaurant_create_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoCoords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autocoords", models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 13, 11, 14, 7, 727149)
            ),
        ),
    ]
