# Generated by Django 4.1.7 on 2023-03-14 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matjipmrk", "0003_autocoords_alter_restaurant_create_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AutoCoords",
        ),
        migrations.AddField(
            model_name="filter",
            name="etc",
            field=models.BooleanField(default="True"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 14, 11, 4, 27, 865717)
            ),
        ),
    ]
