# Generated by Django 4.1.7 on 2023-03-14 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matjipmrk", "0005_alter_restaurant_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 14, 11, 40, 38, 810658)
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="foodtype",
            field=models.CharField(
                choices=[
                    ("korean", "한식"),
                    ("japanese", "일식"),
                    ("chinese", "중식"),
                    ("western", "양식"),
                    ("etc", "기타"),
                ],
                max_length=20,
            ),
        ),
    ]
