# Generated by Django 4.1.7 on 2023-03-14 05:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matjipmrk", "0006_alter_restaurant_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 14, 14, 9, 23, 729804)
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="foodtype",
            field=models.CharField(
                choices=[
                    ("korean", "한식"),
                    ("japanese", "일식"),
                    ("chinese", "중식"),
                    ("western", "양식"),
                    ("etc", "기타"),
                ],
                default="*",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("create_date", models.DateTimeField()),
                (
                    "rst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matjipmrk.restaurant",
                    ),
                ),
            ],
        ),
    ]
